version: '3'

services:
  database:
    build: ./database
    image: wru_database
    ports:
      - 3306
    environment:
      MYSQL_USER: root
      MYSQL_PASS: comsc
      STARTUP_SQL: /tmp/WRUSchema.sql
    container_name: wru_db

  server_1:
    image: wru_server
    links:
      - database
    command: java -jar wru-project-0.0.1-SNAPSHOT.jar --spring.profiles.active=production
    ports:
      - 8080
    container_name: wru_1

  server_2:
    image: wru_server
    links:
      - database
    command: java -jar wru-project-0.0.1-SNAPSHOT.jar --spring.profiles.active=production --server.port=8082
    ports:
      - 8082
    container_name: wru_2

  nginx:
    build: ./nginx
    image: wru_nginx
    links:
      - server_1
      - server_2
    ports:
      - 8081:8081
    container_name: wru_nginx

  jmeter:
    build: ./jmeter
    image: wru_jmeter
    links:
      - nginx
    container_name: wru_jmeter

